### ISSUE TITLE
Problem deploying an app

### ISSUE THREAD

**Issue by jes** [AsteroidOS/meta-smelt-hybris#10]
Apologies if this is not the best repo to create the issue. And also I am aware that this is probably not a bug but a support request, but I don't know where else to go.

I'm following the instructions on https://asteroidos.org/wiki/creating-an-asteroid-app/

I have successfully built the SDK (because I misread and didn't realise that you can simply download a prebuilt one), after making the change to "stime()" that I mentioned in https://github.com/AsteroidOS/meta-smelt-hybris/issues/9#issuecomment-659119030

I have configured QtCreator as described, except the stuff about Qt Versions and Compilers has moved from "Build & Run" to "Kits" in the Options.

I can successfully compile the asteroid-stopwatch app. When I try to run it, QtCreator complains:

> :- 1: error: Local file "/home/jes/build-asteroid-stopwatch-Unnamed-Debug/asteroid-stopwatch.desktop" does not exist.

I have solved this by copying the asteroid-stopwatch.desktop file I generated in ~/asteroid-stopwatch into the build directory. Possibly this is where my next problem comes from:

With .desktop file in place, if I try to run the app, I get this message:

> 11:19:36: Starting /usr/bin/asteroid-stopwatch ...
> qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> Available platform plugins are: hwcomposer, minimal, offscreen, vnc, wayland-egl, wayland.
>
> 11:19:36: Remote process crashed.

But if I SSH into the watch over USB and run the app using `invoker`, it works fine. So presumably something about how QtCreator tries to run the app is not quite right. I'm guessing that it needs different contents in the .desktop file, but can't work out how to proceed.

**Comment by jes** [comment]
I get the same error myself over SSH if I try to execute `asteroid-stopwatch` without using `invoker`, so I thought that might be what QtCreator is doing. I went into the "Projects" mode (?) and "Run Settings" pane, and set "Alternate executable on device" to "/usr/bin/invoker" with "Use this command instead", and set "Command line arguments" to "--type=qtcomponents-qt5 /usr/bin/asteroid-stopwatch", and now it says this:

> 11:36:37: Starting /usr/bin/invoker --type=qtcomponents-qt5 /usr/bin/asteroid-stopwatch...
> qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
>
> Available platform plugins are: hwcomposer, minimal, offscreen, vnc, wayland-egl, wayland.
>
> 11:36:38: Remote process crashed.

Which is the same as before, except now confirms that it is actually trying to run `invoker` instead of `asteroid-stopwatch` directly.

**Comment by MagneFire** [comment]
This is indeed not the best place to place issues like this, generally the best location would be here: https://github.com/AsteroidOS/asteroid/issues

Though I am not familiar with running AsteroidOS apps through QtCreator, this error looks familiar to me. Can you try to set the `QT_QPA_PLATFORM` variable to `wayland`? And maybe also `EGL_PLATFORM` to `wayland`? https://doc.qt.io/qtcreator/creator-run-settings.html has some information that describes adding environment variables.

**Comment by jes** [comment]
OK, thanks. I'll post there next time!

I set those environment variables but they didn't obviously change anything, I'm getting the same errors. I think I can cope with just running stuff through SSH though, so actually this isn't as big a problem as I thought it was. I'm currently printing a pogo pin adapter & have ordered some pogo pins, although I wasn't quite sure what length I needed so I just guessed.

**Comment by MagneFire** [comment]
Weird, but ok :+1:  The documentation also doesn't mention how to do it. Maybe no one succeeded at doing that.

Here is a link to the pogo pins I am using: https://www.aliexpress.com/item/32767984398.html?spm=a2g0s.9042311.0.0.27424c4dmZ2NC1

So total length is around 16.54mm and diameter is around 1.02mm

**Comment by jes** [comment]
Thanks!
